### ISSUE TITLE
show multiple versions for a stack in console

### ISSUE THREAD

**Issue by alohr51** [kabanero-io/kabanero-landing#143]
#### Feature description

Stacks can have multiple versions (since 0.6.0) we will need to show those multiple versions via the console.

Right now we only show 1 version per stack, but there can be multiple.

We will have to wait on the CLI services to implement this. They will probably add these versions to the JSON output for stacks returned in the list stacks endpoint - which we will have to update our code to handle the different output.

---

some more background/context from Tim:

>In the Kabanero CR instance, you have to list multiple collection (or stack) repositories, since it's not currently possible to have two versions of the same stack in the same index.  The Kabanero operator takes care of the rest.  A Collection (or Stack) CR instance is created like this:

```
spec:
  desiredState: active
  name: java-microprofile
  repositoryUrl: https://github.com/kabanero-io/collections/releases/download/0.5.0-rc.3/kabanero-index.yaml
  version: 0.2.21
  versions:
  - desiredState: active
    repositoryUrl: https://github.com/kabanero-io/collections/releases/download/0.5.0-rc.3/kabanero-index.yaml
    version: 0.2.21
  - desiredState: active
    repositoryUrl: https://github.com/kabanero-io/collections/releases/download/0.2.0/kabanero-index.yaml
    version: 0.2.18
```

>This is for a collection, which is more complicated because we had to simultaneously support the old way (one version) with the new way (multiple versions).  The new way would look like this:
```
spec:
  name: java-microprofile
  versions:
  - desiredState: active
    repositoryUrl: https://github.com/kabanero-io/collections/releases/download/0.5.0-rc.3/kabanero-index.yaml
    version: 0.2.21
  - desiredState: active
    repositoryUrl: https://github.com/kabanero-io/collections/releases/download/0.2.0/kabanero-index.yaml
    version: 0.2.18
```
>there is one stack, named java-microprofile and the versions array has two elements, one at version 0.2.21 and one at version 0.2.18.
