### ISSUE TITLE
Create UI for updating kabanero instance

### ISSUE THREAD

**Issue by alohr51** [kabanero-io/kabanero-landing#216]
We will need a nice UI to allow users to update the instance. I am imagining a "edit" link right under the instance name in the accordion that opens a modal with a bunch of fields and a submit button that updates the button.

![image](https://user-images.githubusercontent.com/3623618/78803109-975c1c80-798c-11ea-9d5d-7736f1fd2c1a.png)

On "edit" link click -> there will be a request to get the latest instance information from the instance name (this endpoint _should_ exist already) then the modal will take that fresh CR info from that request and fill in the modal.

This issue is only for creating that modal with 1 or 2 things to edit, we will add more in future edits. The first 2 should be the instance name and enabling/disabling the codereadyworkspace spec value. Example yaml below (but you should be using the kabanero operator bindings api)

```
apiVersion: kabanero.io/v1alpha2
kind: Kabanero
metadata:
  name: kabanero
spec:
  version: "0.8.0"
  codeReadyWorkspaces:
    enable: true
  governancePolicy:
    stackPolicy: activeDigest
```
